query LocationDetail($id: String!) {
  locations(id: $id) {
    id
    versionId
    createdAt
    publishedAt
    data {
      coordinates {
        x
        y
      }
      description {
        en
        ru
        zh
      }
      gallery {
        fileId
        fileName
        hash
        height
        mimeType
        url
        width
      }
      kind
      map {
        fileId
        fileName
        hash
        height
        mimeType
        url
        width
      }
      name {
        en
        ru
        zh
      }
      region_id {
        id
        data {
          climate
          name {
            en
            ru
            zh
          }
        }
      }
    }
  }
}
