query SearchPage($first: Int!) {
  abilities: abilitieses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  blogAuthors: blog_authorses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  blogPosts: blog_postses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  classes: classeses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  dialogs: dialogses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  effects: effectses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  factions: factionses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  heroes: heroeses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  itemTypes: item_typeses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  items: itemses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  landingFeatures: landing_featureses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  landingHero: landing_heros(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  landingTestimonials: landing_testimonialses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  locations: locationses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  monsters: monsterses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  npcs: npcses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  parties: partieses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  quests: questses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  regions: regionses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
  stats: statses(data: { first: $first }) {
    edges {
      node {
        id
        json
        publishedAt
        updatedAt
      }
    }
    totalCount
  }
}
